/* Generated By:JavaCC: Do not edit this line. PigFileParserConstants.java */
package org.apache.pig.tools.parameters;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PigFileParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NEWLINE = 1;
  /** RegularExpression Id. */
  int SPACE = 2;
  /** RegularExpression Id. */
  int COMMENT = 3;
  /** RegularExpression Id. */
  int LETTER = 4;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int SPECIALCHAR = 6;
  /** RegularExpression Id. */
  int DOLLAR = 7;
  /** RegularExpression Id. */
  int DECLARE = 8;
  /** RegularExpression Id. */
  int PIGDEFAULT = 9;
  /** RegularExpression Id. */
  int IDENTIFIER = 10;
  /** RegularExpression Id. */
  int LITERAL = 11;
  /** RegularExpression Id. */
  int SHELLCMD = 12;
  /** RegularExpression Id. */
  int OTHER = 13;
  /** RegularExpression Id. */
  int NOT_OTHER_CHAR = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NEWLINE>",
    "<SPACE>",
    "<COMMENT>",
    "<LETTER>",
    "<DIGIT>",
    "<SPECIALCHAR>",
    "<DOLLAR>",
    "\"%declare\"",
    "\"%default\"",
    "<IDENTIFIER>",
    "<LITERAL>",
    "<SHELLCMD>",
    "<OTHER>",
    "<NOT_OTHER_CHAR>",
  };

}
